---
- name: Verify
  hosts: all

  tasks:
    - name: Check if logrotate file is set up
      command: grep -Fxq "weekly" /etc/logrotate.conf
      register: check_rotate
      check_mode: no
      ignore_errors: yes
      changed_when: no
      
    - name: Assertion test for logrotate
      assert:
          that: check_rotate.rc == 0